Update build_llvm_cosmo.yml

diff --git a/.github/workflows/build_llvm_cosmo.yml b/.github/workflows/build_llvm_cosmo.yml
--- a/.github/workflows/build_llvm_cosmo.yml
+++ b/.github/workflows/build_llvm_cosmo.yml
@@ -38,8 +38,14 @@ jobs:
           unzip -qq android-ndk.zip
           cd $ROOTDIR
 
+          LLVM_VERSION=$(${{ runner.temp }}/android-ndk-r${{inputs.version}}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --version | sed -n 's/.*clang version \([0-9][0-9.]*[a-zA-Z0-9]*\).*/\1/p')
           LLVM_REV=$(${{ runner.temp }}/android-ndk-r${{inputs.version}}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --version | sed -E 's/.*llvm-project ([a-f0-9]{40}).*/\1/' | head -n 1)
           ANDROID_REV=$(grep 'llvm_android/+/.*' "${{ runner.temp }}/android-ndk-r${{inputs.version}}/toolchains/llvm/prebuilt/linux-x86_64/clang_source_info.md" | sed -n 's/.*llvm_android\/\+//; s/\/patches.*//p' | sed 's/\/\+//g; s/^\+//g' | head -n 1)
+
+          if [[ -z "$LLVM_VERSION" ]]; then
+              echo "Failed to extract Google LLVM version."
+              exit 1
+          fi
 
           if [[ -z "$LLVM_REV" ]]; then
               echo "Failed to extract Google LLVM revision."
@@ -51,6 +57,7 @@ jobs:
               exit 1
           fi
 
+          echo "Google LLVM version: $LLVM_VERSION"
           echo "Google LLVM revision: $LLVM_REV"
           echo "llvm_android revision: $ANDROID_REV"
 
@@ -65,10 +72,6 @@ jobs:
           cd ../llvm_android
           git checkout $ANDROID_REV
           cd $ROOTDIR
-
-          if [[ "${{ inputs.version }}" =~ 27 ]]; then
-              curl -LkSs "https://github.com/HomuHomu833/android-ndk-custom/raw/refs/heads/google/patches/cosmo/gcc-14-arm-fix.patch" | git -C "$ROOTDIR/llvm" apply 
-          fi
 
           echo "Applying patches from llvm_android..."
 
@@ -85,8 +88,11 @@ jobs:
 
           rm -rf "$ROOTDIR/../llvm_android"
 
-          MAJOR_VERSION=$(${{ runner.temp }}/android-ndk-r${{inputs.version}}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --version | sed -n 's/.*clang version \([0-9]\+\).*/\1/p')
-          curl -LkSs "https://github.com/HomuHomu833/android-ndk-custom/raw/refs/heads/main/patches/cosmo/llvm-${MAJOR_VERSION}.patch" | git apply
+          curl -LkSs "https://github.com/HomuHomu833/android-ndk-custom/raw/refs/heads/$(git branch --show-current)/patches/cosmo/$LLVM_VERSION/base.patch" | git -C "$ROOTDIR/llvm" apply
+
+          if [[ "${{ inputs.version }}" =~ 27 ]]; then
+              curl -LkSs "https://github.com/HomuHomu833/android-ndk-custom/raw/refs/heads/$(git branch --show-current)/patches/cosmo/$LLVM_VERSION/gcc-14-arm-fix.patch" | git -C "$ROOTDIR/llvm" apply 
+          fi
 
           echo "All patches applied successfully."
 
