Update build_llvm_musl.yml

diff --git a/.github/workflows/build_llvm_musl.yml b/.github/workflows/build_llvm_musl.yml
--- a/.github/workflows/build_llvm_musl.yml
+++ b/.github/workflows/build_llvm_musl.yml
@@ -42,8 +42,14 @@ jobs:
           unzip -qq android-ndk.zip
           cd $ROOTDIR
 
+          LLVM_VERSION=$(${{ runner.temp }}/android-ndk-r${{inputs.version}}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --version | sed -n 's/.*clang version \([0-9][0-9.]*[a-zA-Z0-9]*\).*/\1/p')
           LLVM_REV=$(${{ runner.temp }}/android-ndk-r${{inputs.version}}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --version | sed -E 's/.*llvm-project ([a-f0-9]{40}).*/\1/' | head -n 1)
           ANDROID_REV=$(grep 'llvm_android/+/.*' "${{ runner.temp }}/android-ndk-r${{inputs.version}}/toolchains/llvm/prebuilt/linux-x86_64/clang_source_info.md" | sed -n 's/.*llvm_android\/\+//; s/\/patches.*//p' | sed 's/\/\+//g; s/^\+//g' | head -n 1)
+
+          if [[ -z "$LLVM_VERSION" ]]; then
+              echo "Failed to extract Google LLVM version."
+              exit 1
+          fi
 
           if [[ -z "$LLVM_REV" ]]; then
               echo "Failed to extract Google LLVM revision."
@@ -55,6 +61,7 @@ jobs:
               exit 1
           fi
 
+          echo "Google LLVM version: $LLVM_VERSION"
           echo "Google LLVM revision: $LLVM_REV"
           echo "llvm_android revision: $ANDROID_REV"
 
